export const sampleRuns = [
  {
    id: 1,
    date: new Date(2024, 9, 2),
    time: '18:00',
    distance: 5,
    target_pace: '8:00/mi',
    meetup_location: 'Midtown East',
    qr_code: 'run_1_qr',
    status: 'scheduled',
  },
  {
    id: 2,
    date: new Date(2024, 9, 9),
    time: '19:30',
    distance: 10,
    target_pace: '7:45/mi',
    meetup_location: 'Central Park',
    qr_code: 'run_2_qr',
    status: 'scheduled',
  },
  {
    id: 3,
    date: new Date(2024, 9, 16),
    time: '18:30',
    distance: 5,
    target_pace: '8:15/mi',
    meetup_location: 'Brooklyn Bridge Park',
    qr_code: 'run_3_qr',
    status: 'scheduled',
  },
  {
    id: 4,
    date: new Date(2024, 9, 23),
    time: '20:00',
    distance: 15,
    target_pace: '8:30/mi',
    meetup_location: 'Prospect Park',
    qr_code: 'run_4_qr',
    status: 'scheduled',
  },
  {
    id: 5,
    date: new Date(2024, 10, 6),
    time: '17:30',
    distance: 5,
    target_pace: '7:55/mi',
    meetup_location: 'Hudson River Park',
    qr_code: 'run_5_qr',
    status: 'scheduled',
  },
  {
    id: 6,
    date: new Date(2024, 10, 13),
    time: '21:00',
    distance: 21.1, // Half Marathon in kilometers
    target_pace: '8:20/mi',
    meetup_location: 'Manhattan Waterfront',
    qr_code: 'run_6_qr',
    status: 'scheduled',
  },
  {
    id: 7,
    date: new Date(2024, 10, 20),
    time: '18:45',
    distance: 10,
    target_pace: '7:50/mi',
    meetup_location: 'Riverside Park',
    qr_code: 'run_7_qr',
    status: 'scheduled',
  },
  {
    id: 8,
    date: new Date(2024, 10, 24),
    time: '09:00',
    distance: 5,
    target_pace: '8:05/mi',
    meetup_location: 'Central Park',
    qr_code: 'run_8_qr',
    status: 'scheduled',
  },
  {
    id: 9,
    date: new Date(2024, 10, 27),
    time: '19:15',
    distance: 10,
    target_pace: '8:10/mi',
    meetup_location: 'East River Park',
    qr_code: 'run_9_qr',
    status: 'scheduled',
  },
  {
    id: 10,
    date: new Date(2024, 11, 4),
    time: '17:45',
    distance: 5,
    target_pace: '8:00/mi',
    meetup_location: 'Battery Park',
    qr_code: 'run_10_qr',
    status: 'scheduled',
  },
  {
    id: 11,
    date: new Date(2024, 11, 11),
    time: '18:30',
    distance: 10,
    target_pace: '7:40/mi',
    meetup_location: 'Central Park',
    qr_code: 'run_11_qr',
    status: 'scheduled',
  },
  {
    id: 12,
    date: new Date(2024, 11, 18),
    time: '20:15',
    distance: 15,
    target_pace: '8:25/mi',
    meetup_location: 'Prospect Park',
    qr_code: 'run_12_qr',
    status: 'scheduled',
  },
]
